name: Update branch

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: staging
          force: 1
          githubToken: ${{ secrets.ON_DECK_BOT_TOKEN }}
