name: Update branch

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git branch -f staging
          git push -f origin staging:staging
